"""Add game_code to game_instances

Revision ID: 0be7fb911f81
Revises: d43a2d05e859
Create Date: 2026-05-25 20:42:55.744269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be7fb911f81'
down_revision: Union[str, Sequence[str], None] = 'd43a2d05e859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_instances', sa.Column('game_code', sa.String(length=4), nullable=False))
    op.create_index(op.f('ix_game_instances_game_code'), 'game_instances', ['game_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_instances_game_code'), table_name='game_instances')
    op.drop_column('game_instances', 'game_code')
    # ### end Alembic commands ###
