"""Initial game_instance table

Revision ID: d43a2d05e859
Revises: 
Create Date: 2026-05-25 18:43:29.958367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43a2d05e859'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('nr_of_players', sa.Integer(), nullable=False),
    sa.Column('bot_types', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_instances')
    # ### end Alembic commands ###
